"""create products table

Revision ID: 4715997c47ae
Revises: 
Create Date: 2026-06-23 12:50:09.106286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4715997c47ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('address')
    op.drop_table('event')
    op.drop_table('vehicle')
    op.drop_table('driver')
    op.drop_table('cupons')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("type::text = ANY (ARRAY['CARGA'::character varying, 'DESCARGA'::character varying, 'CHECKPOINT'::character varying, 'ABASTECIMENTO'::character varying]::text[])", name=op.f('checkpoint_type_event')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_event_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_table('cupons',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('discount', sa.NUMERIC(precision=38, scale=2), autoincrement=False, nullable=True),
    sa.Column('valid', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk518r3kqxth464gnm5j7ejsud')),
    sa.PrimaryKeyConstraint('id', name=op.f('cupons_pkey'))
    )
    op.create_table('driver',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_register', postgresql.TIMESTAMP(), server_default=sa.text('LOCALTIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_pkey')),
    sa.UniqueConstraint('cpf', name=op.f('driver_cpf_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plate', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vehicle_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('fk_vehicle_driver')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_pkey')),
    sa.UniqueConstraint('plate', name=op.f('vehicle_plate_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('event',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('event_pkey'))
    )
    op.create_table('address',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uf', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fkey2rx4qsllkdkuo4g1ks243ff')),
    sa.PrimaryKeyConstraint('id', name=op.f('address_pkey')),
    sa.UniqueConstraint('event_id', name=op.f('ukmj870wh3u2tllei9cd0pdtiqm'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('products')
    # ### end Alembic commands ###
